name: Node CI
on: 
    push:
        branches:
            - main
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: npm install, build, and test
              run: |
                npm install
                npm run build
                npm test
            - name: Archive production artifacts
              uses: actions/upload-artifact@v4
              with:
                name: production-artifacts
                path: |
                    dist/
                    !dist/**/*.md
                retention-days: 1
            - name: Archive all project files
              uses: actions/upload-artifact@v4
              with:
                name: project-files
                path: .
            - name: Archive code coverage result
              uses: actions/upload-artifact@v4
              with:
                name: code-coverage
                path: output/test/code-coverage.html
            - name: Download production artifacts
              uses: actions/download-artifact@v4
              with:
                name: project-files
